version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "00:00"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "00:00"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    open-pull-requests-limit: 5
    reviewers:
      - "hgarfer"
    labels:
      - "dependencies"
      - "jekyll"
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      jekyll-ecosystem:
        patterns:
          - "jekyll*"
          - "github-pages"
          - "minima"
        update-types:
          - "minor"
          - "patch"
